url: https://agd.data.gouv.fr
name: Administrateur Général des Données
description: Le site de l'Administrateur Général des Données

lang: fr

github_repository: etalab/agd.data.gouv.fr

include: ["_pages"]

permalink: pretty

exclude:
  - README.md
  - docker-compose.yml
  - circle.yml
  - deploy
  - Gemfile
  - Gemfile.lock
  - vendor
  - .circle
  - node_modules
  - yarn.lock
  - package.json
