backend:
  name: github
  base_url: https://api.staticweb-01.etalab.gouv.fr
  site_domain: agd.data.gouv.fr
  repo: etalab/agd.data.gouv.fr

media_folder: "wp-content/uploads"

# Editorial workflow: validate changes through pull requests
# publish_mode: editorial_workflow
collections:
   - name: "pages"
     label: "Pages"
     folder: "_pages"
     create: true
     fields:
       - {label: "Titre", name: "title", widget: "string"}
       - {label: "Contenu", name: "body", widget: "markdown"}

   - name: "posts"
     label: "Posts"
     folder: "_posts"
     slug: "{{year}}-{{month}}-{{day}}-{{title}}"
     create: true
     fields:
       - {label: "Titre", name: "title", widget: "string"}
       - {label: "Date", name: "date", widget: "string"}
       - {label: "Auteur", name: "author", widget: "string"}
       - {label: "Catégories", name: "categories", widget: "string"}
       - {label: "Image", name: "image", widget: image}
       - {label: "Sous-titre", name: "excerpt", widget: string}
       - {label: "Contenu", name: "body", widget: "markdown"}
