backend:
  name: github
  base_url: https://api.staticweb-01.etalab.gouv.fr
  site_domain: agd.data.gouv.fr
  repo: etalab/agd.data.gouv.fr

media_folder: "wp-content/uploads"

# Editorial workflow: validate changes through pull requests
# publish_mode: editorial_workflow
collections:
   - name: "pages"
     label: "Pages"
     folder: "_pages"
     create: true
     fields:
       - {label: "Titre", name: "title", widget: "string"}
       - {label: "Lien de la page", name: "permalink", widget: "string", default: "/titre-de-la-page/"}
       - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
       - {label: "Contenu", name: "body", widget: "markdown"}

   - name: "posts"
     label: "Posts"
     folder: "_posts"
     slug: "{{year}}-{{month}}-{{day}}-{{title}}"
     create: true
     fields:
       - {label: "Titre", name: "title", widget: "string"}
       - {label: "Date", name: "date", widget: "string"}
       - {label: "Auteur", name: "author", widget: "string"}
       - {label: "Catégories", name: "categories", widget: "string", required: false}
       - {label: "Image", name: "image", widget: image, required: false}
       - {label: "Contenu", name: "body", widget: "markdown"}
